// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Person.proto

package com.pdms.person;

public final class PersonOuterClass {
  private PersonOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PersonOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.pdms.person.Person)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * This is the person age
     * </pre>
     *
     * <code>int32 age = 1;</code>
     */
    int getAge();

    /**
     * <code>string first_name = 2;</code>
     */
    java.lang.String getFirstName();
    /**
     * <code>string first_name = 2;</code>
     */
    com.google.protobuf.ByteString
        getFirstNameBytes();

    /**
     * <code>string last_name = 3;</code>
     */
    java.lang.String getLastName();
    /**
     * <code>string last_name = 3;</code>
     */
    com.google.protobuf.ByteString
        getLastNameBytes();

    /**
     * <pre>
     * Small picture represent a JPEG file
     * </pre>
     *
     * <code>bytes small_pic = 4;</code>
     */
    com.google.protobuf.ByteString getSmallPic();

    /**
     * <code>bool profile_verified = 5;</code>
     */
    boolean getProfileVerified();

    /**
     * <pre>
     * Height of the person in centimeters
     * </pre>
     *
     * <code>float height = 6;</code>
     */
    float getHeight();

    /**
     * <pre>
     * List of phone number which is optional to provide at signup
     * </pre>
     *
     * <code>repeated string phones = 7;</code>
     */
    java.util.List<java.lang.String>
        getPhonesList();
    /**
     * <pre>
     * List of phone number which is optional to provide at signup
     * </pre>
     *
     * <code>repeated string phones = 7;</code>
     */
    int getPhonesCount();
    /**
     * <pre>
     * List of phone number which is optional to provide at signup
     * </pre>
     *
     * <code>repeated string phones = 7;</code>
     */
    java.lang.String getPhones(int index);
    /**
     * <pre>
     * List of phone number which is optional to provide at signup
     * </pre>
     *
     * <code>repeated string phones = 7;</code>
     */
    com.google.protobuf.ByteString
        getPhonesBytes(int index);

    /**
     * <code>.com.pdms.person.Person.EYE_COLOR eye_color = 8;</code>
     */
    int getEyeColorValue();
    /**
     * <code>.com.pdms.person.Person.EYE_COLOR eye_color = 8;</code>
     */
    com.pdms.person.PersonOuterClass.Person.EYE_COLOR getEyeColor();

    /**
     * <code>repeated .com.pdms.person.Person.Address addresses = 9;</code>
     */
    java.util.List<com.pdms.person.PersonOuterClass.Person.Address> 
        getAddressesList();
    /**
     * <code>repeated .com.pdms.person.Person.Address addresses = 9;</code>
     */
    com.pdms.person.PersonOuterClass.Person.Address getAddresses(int index);
    /**
     * <code>repeated .com.pdms.person.Person.Address addresses = 9;</code>
     */
    int getAddressesCount();
    /**
     * <code>repeated .com.pdms.person.Person.Address addresses = 9;</code>
     */
    java.util.List<? extends com.pdms.person.PersonOuterClass.Person.AddressOrBuilder> 
        getAddressesOrBuilderList();
    /**
     * <code>repeated .com.pdms.person.Person.Address addresses = 9;</code>
     */
    com.pdms.person.PersonOuterClass.Person.AddressOrBuilder getAddressesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.pdms.person.Person}
   */
  public  static final class Person extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.pdms.person.Person)
      PersonOrBuilder {
    // Use Person.newBuilder() to construct.
    private Person(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Person() {
      age_ = 0;
      firstName_ = "";
      lastName_ = "";
      smallPic_ = com.google.protobuf.ByteString.EMPTY;
      profileVerified_ = false;
      height_ = 0F;
      phones_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      eyeColor_ = 0;
      addresses_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Person(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              age_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              firstName_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              lastName_ = s;
              break;
            }
            case 34: {

              smallPic_ = input.readBytes();
              break;
            }
            case 40: {

              profileVerified_ = input.readBool();
              break;
            }
            case 53: {

              height_ = input.readFloat();
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
                phones_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000040;
              }
              phones_.add(s);
              break;
            }
            case 64: {
              int rawValue = input.readEnum();

              eyeColor_ = rawValue;
              break;
            }
            case 74: {
              if (!((mutable_bitField0_ & 0x00000100) == 0x00000100)) {
                addresses_ = new java.util.ArrayList<com.pdms.person.PersonOuterClass.Person.Address>();
                mutable_bitField0_ |= 0x00000100;
              }
              addresses_.add(
                  input.readMessage(com.pdms.person.PersonOuterClass.Person.Address.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
          phones_ = phones_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000100) == 0x00000100)) {
          addresses_ = java.util.Collections.unmodifiableList(addresses_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.pdms.person.PersonOuterClass.internal_static_com_pdms_person_Person_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.pdms.person.PersonOuterClass.internal_static_com_pdms_person_Person_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.pdms.person.PersonOuterClass.Person.class, com.pdms.person.PersonOuterClass.Person.Builder.class);
    }

    /**
     * Protobuf enum {@code com.pdms.person.Person.EYE_COLOR}
     */
    public enum EYE_COLOR
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>UNKNOWN_EYE_COLOR = 0;</code>
       */
      UNKNOWN_EYE_COLOR(0),
      /**
       * <code>EYE_GREEN = 1;</code>
       */
      EYE_GREEN(1),
      /**
       * <code>EYE_BLUE = 2;</code>
       */
      EYE_BLUE(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>UNKNOWN_EYE_COLOR = 0;</code>
       */
      public static final int UNKNOWN_EYE_COLOR_VALUE = 0;
      /**
       * <code>EYE_GREEN = 1;</code>
       */
      public static final int EYE_GREEN_VALUE = 1;
      /**
       * <code>EYE_BLUE = 2;</code>
       */
      public static final int EYE_BLUE_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static EYE_COLOR valueOf(int value) {
        return forNumber(value);
      }

      public static EYE_COLOR forNumber(int value) {
        switch (value) {
          case 0: return UNKNOWN_EYE_COLOR;
          case 1: return EYE_GREEN;
          case 2: return EYE_BLUE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<EYE_COLOR>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          EYE_COLOR> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<EYE_COLOR>() {
              public EYE_COLOR findValueByNumber(int number) {
                return EYE_COLOR.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.pdms.person.PersonOuterClass.Person.getDescriptor().getEnumTypes().get(0);
      }

      private static final EYE_COLOR[] VALUES = values();

      public static EYE_COLOR valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private EYE_COLOR(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.pdms.person.Person.EYE_COLOR)
    }

    public interface AddressOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.pdms.person.Person.Address)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>string addressLine1 = 1;</code>
       */
      java.lang.String getAddressLine1();
      /**
       * <code>string addressLine1 = 1;</code>
       */
      com.google.protobuf.ByteString
          getAddressLine1Bytes();

      /**
       * <code>string addressLine2 = 2;</code>
       */
      java.lang.String getAddressLine2();
      /**
       * <code>string addressLine2 = 2;</code>
       */
      com.google.protobuf.ByteString
          getAddressLine2Bytes();

      /**
       * <code>string zipcode = 3;</code>
       */
      java.lang.String getZipcode();
      /**
       * <code>string zipcode = 3;</code>
       */
      com.google.protobuf.ByteString
          getZipcodeBytes();

      /**
       * <code>string city = 4;</code>
       */
      java.lang.String getCity();
      /**
       * <code>string city = 4;</code>
       */
      com.google.protobuf.ByteString
          getCityBytes();

      /**
       * <code>string country = 5;</code>
       */
      java.lang.String getCountry();
      /**
       * <code>string country = 5;</code>
       */
      com.google.protobuf.ByteString
          getCountryBytes();
    }
    /**
     * Protobuf type {@code com.pdms.person.Person.Address}
     */
    public  static final class Address extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:com.pdms.person.Person.Address)
        AddressOrBuilder {
      // Use Address.newBuilder() to construct.
      private Address(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Address() {
        addressLine1_ = "";
        addressLine2_ = "";
        zipcode_ = "";
        city_ = "";
        country_ = "";
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
      }
      private Address(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        int mutable_bitField0_ = 0;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();

                addressLine1_ = s;
                break;
              }
              case 18: {
                java.lang.String s = input.readStringRequireUtf8();

                addressLine2_ = s;
                break;
              }
              case 26: {
                java.lang.String s = input.readStringRequireUtf8();

                zipcode_ = s;
                break;
              }
              case 34: {
                java.lang.String s = input.readStringRequireUtf8();

                city_ = s;
                break;
              }
              case 42: {
                java.lang.String s = input.readStringRequireUtf8();

                country_ = s;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.pdms.person.PersonOuterClass.internal_static_com_pdms_person_Person_Address_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.pdms.person.PersonOuterClass.internal_static_com_pdms_person_Person_Address_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.pdms.person.PersonOuterClass.Person.Address.class, com.pdms.person.PersonOuterClass.Person.Address.Builder.class);
      }

      public static final int ADDRESSLINE1_FIELD_NUMBER = 1;
      private volatile java.lang.Object addressLine1_;
      /**
       * <code>string addressLine1 = 1;</code>
       */
      public java.lang.String getAddressLine1() {
        java.lang.Object ref = addressLine1_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          addressLine1_ = s;
          return s;
        }
      }
      /**
       * <code>string addressLine1 = 1;</code>
       */
      public com.google.protobuf.ByteString
          getAddressLine1Bytes() {
        java.lang.Object ref = addressLine1_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          addressLine1_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int ADDRESSLINE2_FIELD_NUMBER = 2;
      private volatile java.lang.Object addressLine2_;
      /**
       * <code>string addressLine2 = 2;</code>
       */
      public java.lang.String getAddressLine2() {
        java.lang.Object ref = addressLine2_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          addressLine2_ = s;
          return s;
        }
      }
      /**
       * <code>string addressLine2 = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAddressLine2Bytes() {
        java.lang.Object ref = addressLine2_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          addressLine2_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int ZIPCODE_FIELD_NUMBER = 3;
      private volatile java.lang.Object zipcode_;
      /**
       * <code>string zipcode = 3;</code>
       */
      public java.lang.String getZipcode() {
        java.lang.Object ref = zipcode_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          zipcode_ = s;
          return s;
        }
      }
      /**
       * <code>string zipcode = 3;</code>
       */
      public com.google.protobuf.ByteString
          getZipcodeBytes() {
        java.lang.Object ref = zipcode_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          zipcode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int CITY_FIELD_NUMBER = 4;
      private volatile java.lang.Object city_;
      /**
       * <code>string city = 4;</code>
       */
      public java.lang.String getCity() {
        java.lang.Object ref = city_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          city_ = s;
          return s;
        }
      }
      /**
       * <code>string city = 4;</code>
       */
      public com.google.protobuf.ByteString
          getCityBytes() {
        java.lang.Object ref = city_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          city_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int COUNTRY_FIELD_NUMBER = 5;
      private volatile java.lang.Object country_;
      /**
       * <code>string country = 5;</code>
       */
      public java.lang.String getCountry() {
        java.lang.Object ref = country_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          country_ = s;
          return s;
        }
      }
      /**
       * <code>string country = 5;</code>
       */
      public com.google.protobuf.ByteString
          getCountryBytes() {
        java.lang.Object ref = country_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          country_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!getAddressLine1Bytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, addressLine1_);
        }
        if (!getAddressLine2Bytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, addressLine2_);
        }
        if (!getZipcodeBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 3, zipcode_);
        }
        if (!getCityBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 4, city_);
        }
        if (!getCountryBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 5, country_);
        }
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getAddressLine1Bytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, addressLine1_);
        }
        if (!getAddressLine2Bytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, addressLine2_);
        }
        if (!getZipcodeBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, zipcode_);
        }
        if (!getCityBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, city_);
        }
        if (!getCountryBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, country_);
        }
        memoizedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.pdms.person.PersonOuterClass.Person.Address)) {
          return super.equals(obj);
        }
        com.pdms.person.PersonOuterClass.Person.Address other = (com.pdms.person.PersonOuterClass.Person.Address) obj;

        boolean result = true;
        result = result && getAddressLine1()
            .equals(other.getAddressLine1());
        result = result && getAddressLine2()
            .equals(other.getAddressLine2());
        result = result && getZipcode()
            .equals(other.getZipcode());
        result = result && getCity()
            .equals(other.getCity());
        result = result && getCountry()
            .equals(other.getCountry());
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + ADDRESSLINE1_FIELD_NUMBER;
        hash = (53 * hash) + getAddressLine1().hashCode();
        hash = (37 * hash) + ADDRESSLINE2_FIELD_NUMBER;
        hash = (53 * hash) + getAddressLine2().hashCode();
        hash = (37 * hash) + ZIPCODE_FIELD_NUMBER;
        hash = (53 * hash) + getZipcode().hashCode();
        hash = (37 * hash) + CITY_FIELD_NUMBER;
        hash = (53 * hash) + getCity().hashCode();
        hash = (37 * hash) + COUNTRY_FIELD_NUMBER;
        hash = (53 * hash) + getCountry().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.pdms.person.PersonOuterClass.Person.Address parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.pdms.person.PersonOuterClass.Person.Address parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.pdms.person.PersonOuterClass.Person.Address parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.pdms.person.PersonOuterClass.Person.Address parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.pdms.person.PersonOuterClass.Person.Address parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.pdms.person.PersonOuterClass.Person.Address parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.pdms.person.PersonOuterClass.Person.Address parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.pdms.person.PersonOuterClass.Person.Address parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.pdms.person.PersonOuterClass.Person.Address parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.pdms.person.PersonOuterClass.Person.Address parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.pdms.person.PersonOuterClass.Person.Address prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code com.pdms.person.Person.Address}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:com.pdms.person.Person.Address)
          com.pdms.person.PersonOuterClass.Person.AddressOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.pdms.person.PersonOuterClass.internal_static_com_pdms_person_Person_Address_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.pdms.person.PersonOuterClass.internal_static_com_pdms_person_Person_Address_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.pdms.person.PersonOuterClass.Person.Address.class, com.pdms.person.PersonOuterClass.Person.Address.Builder.class);
        }

        // Construct using com.pdms.person.PersonOuterClass.Person.Address.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          addressLine1_ = "";

          addressLine2_ = "";

          zipcode_ = "";

          city_ = "";

          country_ = "";

          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.pdms.person.PersonOuterClass.internal_static_com_pdms_person_Person_Address_descriptor;
        }

        public com.pdms.person.PersonOuterClass.Person.Address getDefaultInstanceForType() {
          return com.pdms.person.PersonOuterClass.Person.Address.getDefaultInstance();
        }

        public com.pdms.person.PersonOuterClass.Person.Address build() {
          com.pdms.person.PersonOuterClass.Person.Address result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.pdms.person.PersonOuterClass.Person.Address buildPartial() {
          com.pdms.person.PersonOuterClass.Person.Address result = new com.pdms.person.PersonOuterClass.Person.Address(this);
          result.addressLine1_ = addressLine1_;
          result.addressLine2_ = addressLine2_;
          result.zipcode_ = zipcode_;
          result.city_ = city_;
          result.country_ = country_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.pdms.person.PersonOuterClass.Person.Address) {
            return mergeFrom((com.pdms.person.PersonOuterClass.Person.Address)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.pdms.person.PersonOuterClass.Person.Address other) {
          if (other == com.pdms.person.PersonOuterClass.Person.Address.getDefaultInstance()) return this;
          if (!other.getAddressLine1().isEmpty()) {
            addressLine1_ = other.addressLine1_;
            onChanged();
          }
          if (!other.getAddressLine2().isEmpty()) {
            addressLine2_ = other.addressLine2_;
            onChanged();
          }
          if (!other.getZipcode().isEmpty()) {
            zipcode_ = other.zipcode_;
            onChanged();
          }
          if (!other.getCity().isEmpty()) {
            city_ = other.city_;
            onChanged();
          }
          if (!other.getCountry().isEmpty()) {
            country_ = other.country_;
            onChanged();
          }
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.pdms.person.PersonOuterClass.Person.Address parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.pdms.person.PersonOuterClass.Person.Address) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private java.lang.Object addressLine1_ = "";
        /**
         * <code>string addressLine1 = 1;</code>
         */
        public java.lang.String getAddressLine1() {
          java.lang.Object ref = addressLine1_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            addressLine1_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string addressLine1 = 1;</code>
         */
        public com.google.protobuf.ByteString
            getAddressLine1Bytes() {
          java.lang.Object ref = addressLine1_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            addressLine1_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string addressLine1 = 1;</code>
         */
        public Builder setAddressLine1(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          addressLine1_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string addressLine1 = 1;</code>
         */
        public Builder clearAddressLine1() {
          
          addressLine1_ = getDefaultInstance().getAddressLine1();
          onChanged();
          return this;
        }
        /**
         * <code>string addressLine1 = 1;</code>
         */
        public Builder setAddressLine1Bytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          addressLine1_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object addressLine2_ = "";
        /**
         * <code>string addressLine2 = 2;</code>
         */
        public java.lang.String getAddressLine2() {
          java.lang.Object ref = addressLine2_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            addressLine2_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string addressLine2 = 2;</code>
         */
        public com.google.protobuf.ByteString
            getAddressLine2Bytes() {
          java.lang.Object ref = addressLine2_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            addressLine2_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string addressLine2 = 2;</code>
         */
        public Builder setAddressLine2(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          addressLine2_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string addressLine2 = 2;</code>
         */
        public Builder clearAddressLine2() {
          
          addressLine2_ = getDefaultInstance().getAddressLine2();
          onChanged();
          return this;
        }
        /**
         * <code>string addressLine2 = 2;</code>
         */
        public Builder setAddressLine2Bytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          addressLine2_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object zipcode_ = "";
        /**
         * <code>string zipcode = 3;</code>
         */
        public java.lang.String getZipcode() {
          java.lang.Object ref = zipcode_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            zipcode_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string zipcode = 3;</code>
         */
        public com.google.protobuf.ByteString
            getZipcodeBytes() {
          java.lang.Object ref = zipcode_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            zipcode_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string zipcode = 3;</code>
         */
        public Builder setZipcode(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          zipcode_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string zipcode = 3;</code>
         */
        public Builder clearZipcode() {
          
          zipcode_ = getDefaultInstance().getZipcode();
          onChanged();
          return this;
        }
        /**
         * <code>string zipcode = 3;</code>
         */
        public Builder setZipcodeBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          zipcode_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object city_ = "";
        /**
         * <code>string city = 4;</code>
         */
        public java.lang.String getCity() {
          java.lang.Object ref = city_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            city_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string city = 4;</code>
         */
        public com.google.protobuf.ByteString
            getCityBytes() {
          java.lang.Object ref = city_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            city_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string city = 4;</code>
         */
        public Builder setCity(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          city_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string city = 4;</code>
         */
        public Builder clearCity() {
          
          city_ = getDefaultInstance().getCity();
          onChanged();
          return this;
        }
        /**
         * <code>string city = 4;</code>
         */
        public Builder setCityBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          city_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object country_ = "";
        /**
         * <code>string country = 5;</code>
         */
        public java.lang.String getCountry() {
          java.lang.Object ref = country_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            country_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string country = 5;</code>
         */
        public com.google.protobuf.ByteString
            getCountryBytes() {
          java.lang.Object ref = country_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            country_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string country = 5;</code>
         */
        public Builder setCountry(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          country_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string country = 5;</code>
         */
        public Builder clearCountry() {
          
          country_ = getDefaultInstance().getCountry();
          onChanged();
          return this;
        }
        /**
         * <code>string country = 5;</code>
         */
        public Builder setCountryBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          country_ = value;
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }


        // @@protoc_insertion_point(builder_scope:com.pdms.person.Person.Address)
      }

      // @@protoc_insertion_point(class_scope:com.pdms.person.Person.Address)
      private static final com.pdms.person.PersonOuterClass.Person.Address DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.pdms.person.PersonOuterClass.Person.Address();
      }

      public static com.pdms.person.PersonOuterClass.Person.Address getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Address>
          PARSER = new com.google.protobuf.AbstractParser<Address>() {
        public Address parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return new Address(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Address> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Address> getParserForType() {
        return PARSER;
      }

      public com.pdms.person.PersonOuterClass.Person.Address getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int AGE_FIELD_NUMBER = 1;
    private int age_;
    /**
     * <pre>
     * This is the person age
     * </pre>
     *
     * <code>int32 age = 1;</code>
     */
    public int getAge() {
      return age_;
    }

    public static final int FIRST_NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object firstName_;
    /**
     * <code>string first_name = 2;</code>
     */
    public java.lang.String getFirstName() {
      java.lang.Object ref = firstName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        firstName_ = s;
        return s;
      }
    }
    /**
     * <code>string first_name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getFirstNameBytes() {
      java.lang.Object ref = firstName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        firstName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LAST_NAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object lastName_;
    /**
     * <code>string last_name = 3;</code>
     */
    public java.lang.String getLastName() {
      java.lang.Object ref = lastName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lastName_ = s;
        return s;
      }
    }
    /**
     * <code>string last_name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getLastNameBytes() {
      java.lang.Object ref = lastName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SMALL_PIC_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString smallPic_;
    /**
     * <pre>
     * Small picture represent a JPEG file
     * </pre>
     *
     * <code>bytes small_pic = 4;</code>
     */
    public com.google.protobuf.ByteString getSmallPic() {
      return smallPic_;
    }

    public static final int PROFILE_VERIFIED_FIELD_NUMBER = 5;
    private boolean profileVerified_;
    /**
     * <code>bool profile_verified = 5;</code>
     */
    public boolean getProfileVerified() {
      return profileVerified_;
    }

    public static final int HEIGHT_FIELD_NUMBER = 6;
    private float height_;
    /**
     * <pre>
     * Height of the person in centimeters
     * </pre>
     *
     * <code>float height = 6;</code>
     */
    public float getHeight() {
      return height_;
    }

    public static final int PHONES_FIELD_NUMBER = 7;
    private com.google.protobuf.LazyStringList phones_;
    /**
     * <pre>
     * List of phone number which is optional to provide at signup
     * </pre>
     *
     * <code>repeated string phones = 7;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getPhonesList() {
      return phones_;
    }
    /**
     * <pre>
     * List of phone number which is optional to provide at signup
     * </pre>
     *
     * <code>repeated string phones = 7;</code>
     */
    public int getPhonesCount() {
      return phones_.size();
    }
    /**
     * <pre>
     * List of phone number which is optional to provide at signup
     * </pre>
     *
     * <code>repeated string phones = 7;</code>
     */
    public java.lang.String getPhones(int index) {
      return phones_.get(index);
    }
    /**
     * <pre>
     * List of phone number which is optional to provide at signup
     * </pre>
     *
     * <code>repeated string phones = 7;</code>
     */
    public com.google.protobuf.ByteString
        getPhonesBytes(int index) {
      return phones_.getByteString(index);
    }

    public static final int EYE_COLOR_FIELD_NUMBER = 8;
    private int eyeColor_;
    /**
     * <code>.com.pdms.person.Person.EYE_COLOR eye_color = 8;</code>
     */
    public int getEyeColorValue() {
      return eyeColor_;
    }
    /**
     * <code>.com.pdms.person.Person.EYE_COLOR eye_color = 8;</code>
     */
    public com.pdms.person.PersonOuterClass.Person.EYE_COLOR getEyeColor() {
      com.pdms.person.PersonOuterClass.Person.EYE_COLOR result = com.pdms.person.PersonOuterClass.Person.EYE_COLOR.valueOf(eyeColor_);
      return result == null ? com.pdms.person.PersonOuterClass.Person.EYE_COLOR.UNRECOGNIZED : result;
    }

    public static final int ADDRESSES_FIELD_NUMBER = 9;
    private java.util.List<com.pdms.person.PersonOuterClass.Person.Address> addresses_;
    /**
     * <code>repeated .com.pdms.person.Person.Address addresses = 9;</code>
     */
    public java.util.List<com.pdms.person.PersonOuterClass.Person.Address> getAddressesList() {
      return addresses_;
    }
    /**
     * <code>repeated .com.pdms.person.Person.Address addresses = 9;</code>
     */
    public java.util.List<? extends com.pdms.person.PersonOuterClass.Person.AddressOrBuilder> 
        getAddressesOrBuilderList() {
      return addresses_;
    }
    /**
     * <code>repeated .com.pdms.person.Person.Address addresses = 9;</code>
     */
    public int getAddressesCount() {
      return addresses_.size();
    }
    /**
     * <code>repeated .com.pdms.person.Person.Address addresses = 9;</code>
     */
    public com.pdms.person.PersonOuterClass.Person.Address getAddresses(int index) {
      return addresses_.get(index);
    }
    /**
     * <code>repeated .com.pdms.person.Person.Address addresses = 9;</code>
     */
    public com.pdms.person.PersonOuterClass.Person.AddressOrBuilder getAddressesOrBuilder(
        int index) {
      return addresses_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (age_ != 0) {
        output.writeInt32(1, age_);
      }
      if (!getFirstNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, firstName_);
      }
      if (!getLastNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, lastName_);
      }
      if (!smallPic_.isEmpty()) {
        output.writeBytes(4, smallPic_);
      }
      if (profileVerified_ != false) {
        output.writeBool(5, profileVerified_);
      }
      if (height_ != 0F) {
        output.writeFloat(6, height_);
      }
      for (int i = 0; i < phones_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, phones_.getRaw(i));
      }
      if (eyeColor_ != com.pdms.person.PersonOuterClass.Person.EYE_COLOR.UNKNOWN_EYE_COLOR.getNumber()) {
        output.writeEnum(8, eyeColor_);
      }
      for (int i = 0; i < addresses_.size(); i++) {
        output.writeMessage(9, addresses_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (age_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, age_);
      }
      if (!getFirstNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, firstName_);
      }
      if (!getLastNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, lastName_);
      }
      if (!smallPic_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, smallPic_);
      }
      if (profileVerified_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, profileVerified_);
      }
      if (height_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(6, height_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < phones_.size(); i++) {
          dataSize += computeStringSizeNoTag(phones_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getPhonesList().size();
      }
      if (eyeColor_ != com.pdms.person.PersonOuterClass.Person.EYE_COLOR.UNKNOWN_EYE_COLOR.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(8, eyeColor_);
      }
      for (int i = 0; i < addresses_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(9, addresses_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.pdms.person.PersonOuterClass.Person)) {
        return super.equals(obj);
      }
      com.pdms.person.PersonOuterClass.Person other = (com.pdms.person.PersonOuterClass.Person) obj;

      boolean result = true;
      result = result && (getAge()
          == other.getAge());
      result = result && getFirstName()
          .equals(other.getFirstName());
      result = result && getLastName()
          .equals(other.getLastName());
      result = result && getSmallPic()
          .equals(other.getSmallPic());
      result = result && (getProfileVerified()
          == other.getProfileVerified());
      result = result && (
          java.lang.Float.floatToIntBits(getHeight())
          == java.lang.Float.floatToIntBits(
              other.getHeight()));
      result = result && getPhonesList()
          .equals(other.getPhonesList());
      result = result && eyeColor_ == other.eyeColor_;
      result = result && getAddressesList()
          .equals(other.getAddressesList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + AGE_FIELD_NUMBER;
      hash = (53 * hash) + getAge();
      hash = (37 * hash) + FIRST_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getFirstName().hashCode();
      hash = (37 * hash) + LAST_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getLastName().hashCode();
      hash = (37 * hash) + SMALL_PIC_FIELD_NUMBER;
      hash = (53 * hash) + getSmallPic().hashCode();
      hash = (37 * hash) + PROFILE_VERIFIED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getProfileVerified());
      hash = (37 * hash) + HEIGHT_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getHeight());
      if (getPhonesCount() > 0) {
        hash = (37 * hash) + PHONES_FIELD_NUMBER;
        hash = (53 * hash) + getPhonesList().hashCode();
      }
      hash = (37 * hash) + EYE_COLOR_FIELD_NUMBER;
      hash = (53 * hash) + eyeColor_;
      if (getAddressesCount() > 0) {
        hash = (37 * hash) + ADDRESSES_FIELD_NUMBER;
        hash = (53 * hash) + getAddressesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.pdms.person.PersonOuterClass.Person parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.pdms.person.PersonOuterClass.Person parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.pdms.person.PersonOuterClass.Person parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.pdms.person.PersonOuterClass.Person parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.pdms.person.PersonOuterClass.Person parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.pdms.person.PersonOuterClass.Person parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.pdms.person.PersonOuterClass.Person parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.pdms.person.PersonOuterClass.Person parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.pdms.person.PersonOuterClass.Person parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.pdms.person.PersonOuterClass.Person parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.pdms.person.PersonOuterClass.Person prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.pdms.person.Person}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.pdms.person.Person)
        com.pdms.person.PersonOuterClass.PersonOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.pdms.person.PersonOuterClass.internal_static_com_pdms_person_Person_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.pdms.person.PersonOuterClass.internal_static_com_pdms_person_Person_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.pdms.person.PersonOuterClass.Person.class, com.pdms.person.PersonOuterClass.Person.Builder.class);
      }

      // Construct using com.pdms.person.PersonOuterClass.Person.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getAddressesFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        age_ = 0;

        firstName_ = "";

        lastName_ = "";

        smallPic_ = com.google.protobuf.ByteString.EMPTY;

        profileVerified_ = false;

        height_ = 0F;

        phones_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000040);
        eyeColor_ = 0;

        if (addressesBuilder_ == null) {
          addresses_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000100);
        } else {
          addressesBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.pdms.person.PersonOuterClass.internal_static_com_pdms_person_Person_descriptor;
      }

      public com.pdms.person.PersonOuterClass.Person getDefaultInstanceForType() {
        return com.pdms.person.PersonOuterClass.Person.getDefaultInstance();
      }

      public com.pdms.person.PersonOuterClass.Person build() {
        com.pdms.person.PersonOuterClass.Person result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.pdms.person.PersonOuterClass.Person buildPartial() {
        com.pdms.person.PersonOuterClass.Person result = new com.pdms.person.PersonOuterClass.Person(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.age_ = age_;
        result.firstName_ = firstName_;
        result.lastName_ = lastName_;
        result.smallPic_ = smallPic_;
        result.profileVerified_ = profileVerified_;
        result.height_ = height_;
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          phones_ = phones_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000040);
        }
        result.phones_ = phones_;
        result.eyeColor_ = eyeColor_;
        if (addressesBuilder_ == null) {
          if (((bitField0_ & 0x00000100) == 0x00000100)) {
            addresses_ = java.util.Collections.unmodifiableList(addresses_);
            bitField0_ = (bitField0_ & ~0x00000100);
          }
          result.addresses_ = addresses_;
        } else {
          result.addresses_ = addressesBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.pdms.person.PersonOuterClass.Person) {
          return mergeFrom((com.pdms.person.PersonOuterClass.Person)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.pdms.person.PersonOuterClass.Person other) {
        if (other == com.pdms.person.PersonOuterClass.Person.getDefaultInstance()) return this;
        if (other.getAge() != 0) {
          setAge(other.getAge());
        }
        if (!other.getFirstName().isEmpty()) {
          firstName_ = other.firstName_;
          onChanged();
        }
        if (!other.getLastName().isEmpty()) {
          lastName_ = other.lastName_;
          onChanged();
        }
        if (other.getSmallPic() != com.google.protobuf.ByteString.EMPTY) {
          setSmallPic(other.getSmallPic());
        }
        if (other.getProfileVerified() != false) {
          setProfileVerified(other.getProfileVerified());
        }
        if (other.getHeight() != 0F) {
          setHeight(other.getHeight());
        }
        if (!other.phones_.isEmpty()) {
          if (phones_.isEmpty()) {
            phones_ = other.phones_;
            bitField0_ = (bitField0_ & ~0x00000040);
          } else {
            ensurePhonesIsMutable();
            phones_.addAll(other.phones_);
          }
          onChanged();
        }
        if (other.eyeColor_ != 0) {
          setEyeColorValue(other.getEyeColorValue());
        }
        if (addressesBuilder_ == null) {
          if (!other.addresses_.isEmpty()) {
            if (addresses_.isEmpty()) {
              addresses_ = other.addresses_;
              bitField0_ = (bitField0_ & ~0x00000100);
            } else {
              ensureAddressesIsMutable();
              addresses_.addAll(other.addresses_);
            }
            onChanged();
          }
        } else {
          if (!other.addresses_.isEmpty()) {
            if (addressesBuilder_.isEmpty()) {
              addressesBuilder_.dispose();
              addressesBuilder_ = null;
              addresses_ = other.addresses_;
              bitField0_ = (bitField0_ & ~0x00000100);
              addressesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getAddressesFieldBuilder() : null;
            } else {
              addressesBuilder_.addAllMessages(other.addresses_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.pdms.person.PersonOuterClass.Person parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.pdms.person.PersonOuterClass.Person) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int age_ ;
      /**
       * <pre>
       * This is the person age
       * </pre>
       *
       * <code>int32 age = 1;</code>
       */
      public int getAge() {
        return age_;
      }
      /**
       * <pre>
       * This is the person age
       * </pre>
       *
       * <code>int32 age = 1;</code>
       */
      public Builder setAge(int value) {
        
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * This is the person age
       * </pre>
       *
       * <code>int32 age = 1;</code>
       */
      public Builder clearAge() {
        
        age_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object firstName_ = "";
      /**
       * <code>string first_name = 2;</code>
       */
      public java.lang.String getFirstName() {
        java.lang.Object ref = firstName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          firstName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string first_name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getFirstNameBytes() {
        java.lang.Object ref = firstName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          firstName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string first_name = 2;</code>
       */
      public Builder setFirstName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        firstName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string first_name = 2;</code>
       */
      public Builder clearFirstName() {
        
        firstName_ = getDefaultInstance().getFirstName();
        onChanged();
        return this;
      }
      /**
       * <code>string first_name = 2;</code>
       */
      public Builder setFirstNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        firstName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object lastName_ = "";
      /**
       * <code>string last_name = 3;</code>
       */
      public java.lang.String getLastName() {
        java.lang.Object ref = lastName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          lastName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string last_name = 3;</code>
       */
      public com.google.protobuf.ByteString
          getLastNameBytes() {
        java.lang.Object ref = lastName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lastName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string last_name = 3;</code>
       */
      public Builder setLastName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        lastName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string last_name = 3;</code>
       */
      public Builder clearLastName() {
        
        lastName_ = getDefaultInstance().getLastName();
        onChanged();
        return this;
      }
      /**
       * <code>string last_name = 3;</code>
       */
      public Builder setLastNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        lastName_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString smallPic_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * Small picture represent a JPEG file
       * </pre>
       *
       * <code>bytes small_pic = 4;</code>
       */
      public com.google.protobuf.ByteString getSmallPic() {
        return smallPic_;
      }
      /**
       * <pre>
       * Small picture represent a JPEG file
       * </pre>
       *
       * <code>bytes small_pic = 4;</code>
       */
      public Builder setSmallPic(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        smallPic_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Small picture represent a JPEG file
       * </pre>
       *
       * <code>bytes small_pic = 4;</code>
       */
      public Builder clearSmallPic() {
        
        smallPic_ = getDefaultInstance().getSmallPic();
        onChanged();
        return this;
      }

      private boolean profileVerified_ ;
      /**
       * <code>bool profile_verified = 5;</code>
       */
      public boolean getProfileVerified() {
        return profileVerified_;
      }
      /**
       * <code>bool profile_verified = 5;</code>
       */
      public Builder setProfileVerified(boolean value) {
        
        profileVerified_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool profile_verified = 5;</code>
       */
      public Builder clearProfileVerified() {
        
        profileVerified_ = false;
        onChanged();
        return this;
      }

      private float height_ ;
      /**
       * <pre>
       * Height of the person in centimeters
       * </pre>
       *
       * <code>float height = 6;</code>
       */
      public float getHeight() {
        return height_;
      }
      /**
       * <pre>
       * Height of the person in centimeters
       * </pre>
       *
       * <code>float height = 6;</code>
       */
      public Builder setHeight(float value) {
        
        height_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Height of the person in centimeters
       * </pre>
       *
       * <code>float height = 6;</code>
       */
      public Builder clearHeight() {
        
        height_ = 0F;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList phones_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensurePhonesIsMutable() {
        if (!((bitField0_ & 0x00000040) == 0x00000040)) {
          phones_ = new com.google.protobuf.LazyStringArrayList(phones_);
          bitField0_ |= 0x00000040;
         }
      }
      /**
       * <pre>
       * List of phone number which is optional to provide at signup
       * </pre>
       *
       * <code>repeated string phones = 7;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getPhonesList() {
        return phones_.getUnmodifiableView();
      }
      /**
       * <pre>
       * List of phone number which is optional to provide at signup
       * </pre>
       *
       * <code>repeated string phones = 7;</code>
       */
      public int getPhonesCount() {
        return phones_.size();
      }
      /**
       * <pre>
       * List of phone number which is optional to provide at signup
       * </pre>
       *
       * <code>repeated string phones = 7;</code>
       */
      public java.lang.String getPhones(int index) {
        return phones_.get(index);
      }
      /**
       * <pre>
       * List of phone number which is optional to provide at signup
       * </pre>
       *
       * <code>repeated string phones = 7;</code>
       */
      public com.google.protobuf.ByteString
          getPhonesBytes(int index) {
        return phones_.getByteString(index);
      }
      /**
       * <pre>
       * List of phone number which is optional to provide at signup
       * </pre>
       *
       * <code>repeated string phones = 7;</code>
       */
      public Builder setPhones(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePhonesIsMutable();
        phones_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * List of phone number which is optional to provide at signup
       * </pre>
       *
       * <code>repeated string phones = 7;</code>
       */
      public Builder addPhones(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePhonesIsMutable();
        phones_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * List of phone number which is optional to provide at signup
       * </pre>
       *
       * <code>repeated string phones = 7;</code>
       */
      public Builder addAllPhones(
          java.lang.Iterable<java.lang.String> values) {
        ensurePhonesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, phones_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * List of phone number which is optional to provide at signup
       * </pre>
       *
       * <code>repeated string phones = 7;</code>
       */
      public Builder clearPhones() {
        phones_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * List of phone number which is optional to provide at signup
       * </pre>
       *
       * <code>repeated string phones = 7;</code>
       */
      public Builder addPhonesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensurePhonesIsMutable();
        phones_.add(value);
        onChanged();
        return this;
      }

      private int eyeColor_ = 0;
      /**
       * <code>.com.pdms.person.Person.EYE_COLOR eye_color = 8;</code>
       */
      public int getEyeColorValue() {
        return eyeColor_;
      }
      /**
       * <code>.com.pdms.person.Person.EYE_COLOR eye_color = 8;</code>
       */
      public Builder setEyeColorValue(int value) {
        eyeColor_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.com.pdms.person.Person.EYE_COLOR eye_color = 8;</code>
       */
      public com.pdms.person.PersonOuterClass.Person.EYE_COLOR getEyeColor() {
        com.pdms.person.PersonOuterClass.Person.EYE_COLOR result = com.pdms.person.PersonOuterClass.Person.EYE_COLOR.valueOf(eyeColor_);
        return result == null ? com.pdms.person.PersonOuterClass.Person.EYE_COLOR.UNRECOGNIZED : result;
      }
      /**
       * <code>.com.pdms.person.Person.EYE_COLOR eye_color = 8;</code>
       */
      public Builder setEyeColor(com.pdms.person.PersonOuterClass.Person.EYE_COLOR value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        eyeColor_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.com.pdms.person.Person.EYE_COLOR eye_color = 8;</code>
       */
      public Builder clearEyeColor() {
        
        eyeColor_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.pdms.person.PersonOuterClass.Person.Address> addresses_ =
        java.util.Collections.emptyList();
      private void ensureAddressesIsMutable() {
        if (!((bitField0_ & 0x00000100) == 0x00000100)) {
          addresses_ = new java.util.ArrayList<com.pdms.person.PersonOuterClass.Person.Address>(addresses_);
          bitField0_ |= 0x00000100;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.pdms.person.PersonOuterClass.Person.Address, com.pdms.person.PersonOuterClass.Person.Address.Builder, com.pdms.person.PersonOuterClass.Person.AddressOrBuilder> addressesBuilder_;

      /**
       * <code>repeated .com.pdms.person.Person.Address addresses = 9;</code>
       */
      public java.util.List<com.pdms.person.PersonOuterClass.Person.Address> getAddressesList() {
        if (addressesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(addresses_);
        } else {
          return addressesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.pdms.person.Person.Address addresses = 9;</code>
       */
      public int getAddressesCount() {
        if (addressesBuilder_ == null) {
          return addresses_.size();
        } else {
          return addressesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.pdms.person.Person.Address addresses = 9;</code>
       */
      public com.pdms.person.PersonOuterClass.Person.Address getAddresses(int index) {
        if (addressesBuilder_ == null) {
          return addresses_.get(index);
        } else {
          return addressesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.pdms.person.Person.Address addresses = 9;</code>
       */
      public Builder setAddresses(
          int index, com.pdms.person.PersonOuterClass.Person.Address value) {
        if (addressesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAddressesIsMutable();
          addresses_.set(index, value);
          onChanged();
        } else {
          addressesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.pdms.person.Person.Address addresses = 9;</code>
       */
      public Builder setAddresses(
          int index, com.pdms.person.PersonOuterClass.Person.Address.Builder builderForValue) {
        if (addressesBuilder_ == null) {
          ensureAddressesIsMutable();
          addresses_.set(index, builderForValue.build());
          onChanged();
        } else {
          addressesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.pdms.person.Person.Address addresses = 9;</code>
       */
      public Builder addAddresses(com.pdms.person.PersonOuterClass.Person.Address value) {
        if (addressesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAddressesIsMutable();
          addresses_.add(value);
          onChanged();
        } else {
          addressesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.pdms.person.Person.Address addresses = 9;</code>
       */
      public Builder addAddresses(
          int index, com.pdms.person.PersonOuterClass.Person.Address value) {
        if (addressesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAddressesIsMutable();
          addresses_.add(index, value);
          onChanged();
        } else {
          addressesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.pdms.person.Person.Address addresses = 9;</code>
       */
      public Builder addAddresses(
          com.pdms.person.PersonOuterClass.Person.Address.Builder builderForValue) {
        if (addressesBuilder_ == null) {
          ensureAddressesIsMutable();
          addresses_.add(builderForValue.build());
          onChanged();
        } else {
          addressesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.pdms.person.Person.Address addresses = 9;</code>
       */
      public Builder addAddresses(
          int index, com.pdms.person.PersonOuterClass.Person.Address.Builder builderForValue) {
        if (addressesBuilder_ == null) {
          ensureAddressesIsMutable();
          addresses_.add(index, builderForValue.build());
          onChanged();
        } else {
          addressesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.pdms.person.Person.Address addresses = 9;</code>
       */
      public Builder addAllAddresses(
          java.lang.Iterable<? extends com.pdms.person.PersonOuterClass.Person.Address> values) {
        if (addressesBuilder_ == null) {
          ensureAddressesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, addresses_);
          onChanged();
        } else {
          addressesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.pdms.person.Person.Address addresses = 9;</code>
       */
      public Builder clearAddresses() {
        if (addressesBuilder_ == null) {
          addresses_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000100);
          onChanged();
        } else {
          addressesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.pdms.person.Person.Address addresses = 9;</code>
       */
      public Builder removeAddresses(int index) {
        if (addressesBuilder_ == null) {
          ensureAddressesIsMutable();
          addresses_.remove(index);
          onChanged();
        } else {
          addressesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.pdms.person.Person.Address addresses = 9;</code>
       */
      public com.pdms.person.PersonOuterClass.Person.Address.Builder getAddressesBuilder(
          int index) {
        return getAddressesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.pdms.person.Person.Address addresses = 9;</code>
       */
      public com.pdms.person.PersonOuterClass.Person.AddressOrBuilder getAddressesOrBuilder(
          int index) {
        if (addressesBuilder_ == null) {
          return addresses_.get(index);  } else {
          return addressesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.pdms.person.Person.Address addresses = 9;</code>
       */
      public java.util.List<? extends com.pdms.person.PersonOuterClass.Person.AddressOrBuilder> 
           getAddressesOrBuilderList() {
        if (addressesBuilder_ != null) {
          return addressesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(addresses_);
        }
      }
      /**
       * <code>repeated .com.pdms.person.Person.Address addresses = 9;</code>
       */
      public com.pdms.person.PersonOuterClass.Person.Address.Builder addAddressesBuilder() {
        return getAddressesFieldBuilder().addBuilder(
            com.pdms.person.PersonOuterClass.Person.Address.getDefaultInstance());
      }
      /**
       * <code>repeated .com.pdms.person.Person.Address addresses = 9;</code>
       */
      public com.pdms.person.PersonOuterClass.Person.Address.Builder addAddressesBuilder(
          int index) {
        return getAddressesFieldBuilder().addBuilder(
            index, com.pdms.person.PersonOuterClass.Person.Address.getDefaultInstance());
      }
      /**
       * <code>repeated .com.pdms.person.Person.Address addresses = 9;</code>
       */
      public java.util.List<com.pdms.person.PersonOuterClass.Person.Address.Builder> 
           getAddressesBuilderList() {
        return getAddressesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.pdms.person.PersonOuterClass.Person.Address, com.pdms.person.PersonOuterClass.Person.Address.Builder, com.pdms.person.PersonOuterClass.Person.AddressOrBuilder> 
          getAddressesFieldBuilder() {
        if (addressesBuilder_ == null) {
          addressesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.pdms.person.PersonOuterClass.Person.Address, com.pdms.person.PersonOuterClass.Person.Address.Builder, com.pdms.person.PersonOuterClass.Person.AddressOrBuilder>(
                  addresses_,
                  ((bitField0_ & 0x00000100) == 0x00000100),
                  getParentForChildren(),
                  isClean());
          addresses_ = null;
        }
        return addressesBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.pdms.person.Person)
    }

    // @@protoc_insertion_point(class_scope:com.pdms.person.Person)
    private static final com.pdms.person.PersonOuterClass.Person DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.pdms.person.PersonOuterClass.Person();
    }

    public static com.pdms.person.PersonOuterClass.Person getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Person>
        PARSER = new com.google.protobuf.AbstractParser<Person>() {
      public Person parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Person(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Person> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Person> getParserForType() {
      return PARSER;
    }

    public com.pdms.person.PersonOuterClass.Person getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_pdms_person_Person_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_pdms_person_Person_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_pdms_person_Person_Address_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_pdms_person_Person_Address_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Person.proto\022\017com.pdms.person\"\233\003\n\006Pers" +
      "on\022\013\n\003age\030\001 \001(\005\022\022\n\nfirst_name\030\002 \001(\t\022\021\n\tl" +
      "ast_name\030\003 \001(\t\022\021\n\tsmall_pic\030\004 \001(\014\022\030\n\020pro" +
      "file_verified\030\005 \001(\010\022\016\n\006height\030\006 \001(\002\022\016\n\006p" +
      "hones\030\007 \003(\t\0224\n\teye_color\030\010 \001(\0162!.com.pdm" +
      "s.person.Person.EYE_COLOR\0222\n\taddresses\030\t" +
      " \003(\0132\037.com.pdms.person.Person.Address\032e\n" +
      "\007Address\022\024\n\014addressLine1\030\001 \001(\t\022\024\n\014addres" +
      "sLine2\030\002 \001(\t\022\017\n\007zipcode\030\003 \001(\t\022\014\n\004city\030\004 " +
      "\001(\t\022\017\n\007country\030\005 \001(\t\"?\n\tEYE_COLOR\022\025\n\021UNK",
      "NOWN_EYE_COLOR\020\000\022\r\n\tEYE_GREEN\020\001\022\014\n\010EYE_B" +
      "LUE\020\002b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_pdms_person_Person_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_pdms_person_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_pdms_person_Person_descriptor,
        new java.lang.String[] { "Age", "FirstName", "LastName", "SmallPic", "ProfileVerified", "Height", "Phones", "EyeColor", "Addresses", });
    internal_static_com_pdms_person_Person_Address_descriptor =
      internal_static_com_pdms_person_Person_descriptor.getNestedTypes().get(0);
    internal_static_com_pdms_person_Person_Address_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_pdms_person_Person_Address_descriptor,
        new java.lang.String[] { "AddressLine1", "AddressLine2", "Zipcode", "City", "Country", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
